# TypeProf 0.31.0

# lib/07/ticket.rb
class Ticket
  @fare: Integer
  @stamped_at: String | nil

  def initialize: (Integer) -> void
  def fare: () -> Integer
  def stamped_at: () -> (String | nil)
  
  def stamp: (String) -> void
end
